services:
- type: web
  name: chatbot-backend
  env: python
  plan: free
  region: oregon
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn app:app"
  envVars:
  - key: GOOGLE_API_KEY
    sync: true
